### ISSUE TITLE
about the datasetter.py

### ISSUE THREAD

**Issue by Bhongcheng** [Lee-Gihun/FedNTD#2]
![image](https://user-images.githubusercontent.com/90205287/228213268-869fa100-fccb-49c6-bf9b-b4f4e1de2006.png)

Hi, I wonder whether the training data is transformed twice?

**Comment by Bhongcheng** [comment]
first...   
 def _build_truncated_dataset(self):
        base_dataset = MNIST(
            self.root, self.train, self.transform, None, self.download
        )

second...
  def __getitem__(self, index):
      img, targets = self.data[index], self.targets[index]
      if self.transform is not None:
          img = self.transform(img)

      return img, targets

**Comment by Bhongcheng** [comment]
When I set the dataset mint, it has error 

Traceback (most recent call last):
  File "/home/bhc/Desktop/back_up/FedLearn/main.py", line 155, in <module>
    main(opt)
  File "/home/bhc/Desktop/back_up/FedLearn/main.py", line 100, in main
    server.run()
  File "/home/bhc/Desktop/back_up/FedLearn/algorithms/BaseServer.py", line 53, in run
    test_acc = evaluate_model(
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/bhc/Desktop/back_up/FedLearn/algorithms/measures.py", line 18, in evaluate_model
    for data, targets in dataloader:
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bhc/Desktop/back_up/FedLearn/train_tools/preprocessing/mnist/datasets.py", line 35, in __getitem__
    img = self.transform(img)
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 94, in __call__
    img = t(img)
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 134, in __call__
    return F.to_tensor(pic)
  File "/home/bhc/anaconda3/envs/bhc/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 138, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>

**Comment by Bhongcheng** [comment]
It seems that in the mnist setting, the valid_transform should add "transforms.ToPILImage()"
<img width="764" alt="image" src="https://user-images.githubusercontent.com/90205287/228539943-40725882-9b5b-45b8-8d35-4b2467123040.png">

Besides, it seems that I have understand my first question about "transform twice".........

**Comment by zhanglong-web** [comment]
为什么这个代码在运行时，会运行这么久呀，我把wandb那些都注释了，本地5轮，用的gpu跑还是好慢呀

**Comment by Lee-Gihun** [comment]
Sorry for the late reply. I missed testing on the MNIST setting after refactoring. Thank you for letting me know.

> It seems that in the mnist setting, the valid_transform should add "transforms.ToPILImage()" <img alt="image" width="764" src="https://user-images.githubusercontent.com/90205287/228539943-40725882-9b5b-45b8-8d35-4b2467123040.png">
> 
> Besides, it seems that I have understand my first question about "transform twice".........


When I translated, you're asking about the running time issue.
> 为什么这个代码在运行时，会运行这么久呀，我把wandb那些都注释了，本地5轮，用的gpu跑还是好慢呀

I guess the issue comes from CPU bottleneck, especially if the `nvidia-smi` command shows you low gpu utils. As I implemented by building dataloader for each client, data loading depends on the available cpu resource.
